// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Endbands.Models.Event = (function(_super) {

    __extends(Event, _super);

    function Event() {
      return Event.__super__.constructor.apply(this, arguments);
    }

    Event.prototype.defaults = {
      date: "-/-",
      pages: 0
    };

    Event.prototype.initialize = function(data) {
      var date, day, month;
      if (!data.date) {
        date = new Date();
      } else {
        date = new Date(data.date);
      }
      month = date.getMonth();
      day = date.getDate();
      return this.set("date", month + 1 + "/" + day);
    };

    return Event;

  })(Backbone.Model);

  Endbands.Collections.Events = (function(_super) {

    __extends(Events, _super);

    function Events() {
      return Events.__super__.constructor.apply(this, arguments);
    }

    Events.prototype.model = Endbands.Models.Event;

    Events.prototype.getLength = function() {
      return this.length;
    };

    Events.prototype.comparator = function(ev) {
      return -ev.get("date");
    };

    return Events;

  })(Backbone.Collection);

  Endbands.Models.Book = (function(_super) {

    __extends(Book, _super);

    function Book() {
      return Book.__super__.constructor.apply(this, arguments);
    }

    Book.prototype.defaults = {
      title: "Untitled",
      author: {
        first: "first",
        last: "last"
      },
      eventCount: 0,
      eventAvg: 0,
      eventTotal: 0,
      library: 0,
      pageCount: "---",
      events: new Endbands.Collections.Events()
    };

    Book.prototype.initialize = function(data) {
      return this.set("events", new Endbands.Collections.Events(data.events));
    };

    return Book;

  })(Backbone.Model);

  Endbands.Collections.Books = (function(_super) {

    __extends(Books, _super);

    function Books() {
      return Books.__super__.constructor.apply(this, arguments);
    }

    Books.prototype.model = Endbands.Models.Book;

    return Books;

  })(Backbone.Collection);

}).call(this);
